[package]
name = "space_invaders_classic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_rapier2d = "0.12.1"
bevy = "0.6.1"
rand = "0.8.5"